[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Nice URL for the function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
